# Generated by Django 5.2.16 on 2026-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
